liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
  filter_sets:
    cache: ~
    speaker_size:
      filters:
        relative_resize: {heighten: 232 }
        crop: { size: [ 232, 232 ], start: [ 0, 0 ] }
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
    partner:
      filters:
        downscale:
          max: [280, 150]
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
    upload_image:
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
    static_image_438_331:
      filters:
        downscale:
          max: [438, 331]
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
    static_image_211_332:
      filters:
        downscale:
          max: [211, 332]
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }
    static_image_211_158:
      filters:
        downscale:
          max: [211, 158]
      post_processors:
        jpegoptim: { strip_all: true, max: 80, progressive: true }